
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMENT DELIMITER KEY LISTVALUE SECTIONTITLE VALUEtoml : title sections title : KEY DELIMITER VALUEsections : sections section\n                | sectionsection : SECTIONTITLE conteudoconteudo : conteudo section \n                | conteudo KEY DELIMITER VALUE \n                | KEY DELIMITER VALUE\n                | section'
    
_lr_action_items = {'KEY':([0,6,9,10,13,17,18,],[3,11,14,-9,-6,-8,-7,]),'$end':([1,4,5,8,9,10,13,17,18,],[0,-1,-4,-3,-5,-9,-6,-8,-7,]),'SECTIONTITLE':([2,4,5,6,8,9,10,12,13,17,18,],[6,6,-4,6,-3,6,-9,-2,-6,-8,-7,]),'DELIMITER':([3,11,14,],[7,15,16,]),'VALUE':([7,15,16,],[12,17,18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'toml':([0,],[1,]),'title':([0,],[2,]),'sections':([2,],[4,]),'section':([2,4,6,9,],[5,8,10,13,]),'conteudo':([6,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> toml","S'",1,None,None,None),
  ('toml -> title sections','toml',2,'p_tabela','tomlyacc.py',7),
  ('title -> KEY DELIMITER VALUE','title',3,'p_title','tomlyacc.py',13),
  ('sections -> sections section','sections',2,'p_sections','tomlyacc.py',19),
  ('sections -> section','sections',1,'p_sections','tomlyacc.py',20),
  ('section -> SECTIONTITLE conteudo','section',2,'p_section','tomlyacc.py',32),
  ('conteudo -> conteudo section','conteudo',2,'p_conteudo','tomlyacc.py',39),
  ('conteudo -> conteudo KEY DELIMITER VALUE','conteudo',4,'p_conteudo','tomlyacc.py',40),
  ('conteudo -> KEY DELIMITER VALUE','conteudo',3,'p_conteudo','tomlyacc.py',41),
  ('conteudo -> section','conteudo',1,'p_conteudo','tomlyacc.py',42),
]
