title = "Treino Teste"

subtitle = " Processamento de Linguagens"

authors = "Claudia, Paulo, Tiago" 

clube = "Futebol Clube do Porto"

#Documento de jogadores e alguns sócios

[jogadores]
[jogadores.principais.guardaredes]
"Agustin Marchesin" = nome 
"Diogo Costa" = "nome"


[jogadores.principais.lateral]
[jogadores.principais.lateral.Direito]
"Wilson Manafa" = nome


[jogadores.principais.lateral.Esquerdo]
"Zaidu Sanusi" = nome


[jogadores.principais.Defesa]
"Chancel Mbemba" = nome
"Pepe" = nome

[jogadores.principais.meiocampo]
"Marko Grujic" = nome
"Otavio Monteiro" = nome

[jogadores.principais.atacante]
"Mehdi Taremi" = nome
"Evanilson" = nome 
"Toni Martinez" = nome 




[ListaSocios]
nome = "listasocios"
cores = [azul, verde, vermelho]
data = 26-05-2023
horas = 12:50:00
15 = "numero socios"


[socios.1]
nome = "Maria das Cruzes Azevedo"
idade = 45
email = "Mariacruz@example.com"
categoria = "Socio"
cota1 = 300
dataadesao = 1979-05-27T00:32:00.999999

[socios.2]
nome = "Ana Clara Santos"
idade = 30
email = "ana.santos@example.com"
categoria = "Adepto"
cota2 = 150
dataadesao = 2023-01-15

[socios.3]
nome = "Pedro Sousa"
idade = 52
email = "pedro.sousa@example.com"
categoria = "Socio"
cota3 = 300
dataadesao = 2021-11-02

[socios.4]
nome = "Mariana Costa"
idade = 37
email = "mariana.costa@example.com"
categoria = "Adepto"
cota4 = 150
dataadesao = 2022-09-18

[socios.5]
nome = "Tiago Ferreira"
idade = 29
email = "tiago.ferreira@example.com"
categoria = "Socio"
cota5 = 300
dataadesao = 2023-03-07

[socios.6]
nome = "Carolina Oliveira"
idade = 41
email = "carolina.oliveira@example.com"
categoria = "Adepto"
cota6 = 150
dataadesao = 2022-06-30

[socios.7]
nome = "Ricardo Lima"
idade = 33
email = "ricardo.lima@example.com"
categoria = "Socio"
cota7 = 300
dataadesao = 2021-08-10

[socios.8]
nome = "Sara Mendes"
idade = 48
email = "sara.mendes@example.com"
categoria = "Adepto"
cota8 = 150
dataadesao = 2023-02-11

[socios.9]
nome = "Hugo Fernandes"
outrosocio.filho = "Carlos"
idade = 36
email = "hugo.fernandes@example.com"
categoria = "Socio"
cota9 = [300,100]
dataadesao = 2022-10-25

[socios.10]
nome = "Maria Santos"
idade = 27
email = "maria.santos@example.com"
categoria = "Adepto"
cota10 = 150
dataadesao = 2023-04-05

[socios.11]
nome = "Gustavo Costa"
idade = 39
email = "gustavo.costa@example.com"
categoria = "Socio"
cota11 = 300
dataadesao = 2021-12-13

[socios.12]
nome = "Marta Sousa"
idade = 43
email = "marta.sousa@example.com"
categoria = "Adepto"
cota12 = 150
dataadesao = 2022-07-22

[socios.13]
nome = "Francisco Oliveira"
idade = 31
email = "francisco.oliveira@example.com"
categoria = "Socio"
cota13 = 300
dataadesao = 2023-05-10


[socios.14]
nome = "Maria das Cruzes Azevedo"
idade = 45
email = "Mariacruz@example.com"
categoria = "Socio"
300 = "cota1"
dataadesao = 2022-04-23




[socio.15.lugaranual]
nome = "Miguel Pereira"
idade = 34
email = "miguel.pereira@example.com"
categoria = "Socio"
cota14 = [300,100]
dataadesao = 2022-08-28
pagamento = "valido"


[[Pagamentos.pendentes]]
nome= "Carlos Almeida"
valor = 10.0

[[Pagamentos.pendentes]]
nome= "Miguel Pereira"
valor = 120
3.20 = "secao"

[[Pagamentos.pendentes]]